/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Prieto
 */
public class VPanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VPanelPrincipal
     */
    public VPanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMinusculas = new javax.swing.JCheckBox();
        jCheckBoxMayusculas = new javax.swing.JCheckBox();
        jCheckBoxNumeros = new javax.swing.JCheckBox();
        jCheckBoxSimbolos = new javax.swing.JCheckBox();
        jCheckBoxCaracterEspecialMinusculas = new javax.swing.JCheckBox();
        jCheckBoxCaracterEspecialMayusculas = new javax.swing.JCheckBox();
        jSliderLongitudPass = new javax.swing.JSlider();
        jLabelLongitudPass = new javax.swing.JLabel();
        jButtonCrearPass = new javax.swing.JButton();
        jLabelNoPass = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonCopy = new javax.swing.JButton();
        jLabelPasswordCopied = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setPreferredSize(new java.awt.Dimension(500, 400));

        jCheckBoxMinusculas.setText("Lowercase (abc)");
        jCheckBoxMinusculas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMinusculasStateChanged(evt);
            }
        });

        jCheckBoxMayusculas.setText("Uppercase (ABC)");
        jCheckBoxMayusculas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMayusculasStateChanged(evt);
            }
        });

        jCheckBoxNumeros.setText("Numbers (123)");
        jCheckBoxNumeros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxNumerosStateChanged(evt);
            }
        });

        jCheckBoxSimbolos.setText("Symbols (@#$)");
        jCheckBoxSimbolos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBoxSimbolos.setFocusable(false);
        jCheckBoxSimbolos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxSimbolosStateChanged(evt);
            }
        });

        jCheckBoxCaracterEspecialMinusculas.setText("Use 'ñ', 'ç'");
        jCheckBoxCaracterEspecialMinusculas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxCaracterEspecialMinusculasStateChanged(evt);
            }
        });
        jCheckBoxCaracterEspecialMinusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCaracterEspecialMinusculasActionPerformed(evt);
            }
        });

        jCheckBoxCaracterEspecialMayusculas.setText("Use 'Ñ', 'Ç'");
        jCheckBoxCaracterEspecialMayusculas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxCaracterEspecialMayusculasStateChanged(evt);
            }
        });

        jSliderLongitudPass.setMajorTickSpacing(4);
        jSliderLongitudPass.setMaximum(32);
        jSliderLongitudPass.setMinimum(4);
        jSliderLongitudPass.setMinorTickSpacing(1);
        jSliderLongitudPass.setValue(8);
        jSliderLongitudPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderLongitudPassStateChanged(evt);
            }
        });

        jLabelLongitudPass.setText("Password length: ");

        jButtonCrearPass.setText("Generate password");
        jButtonCrearPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPassActionPerformed(evt);
            }
        });

        jLabelNoPass.setText("Password:");

        jTextFieldPassword.setEditable(false);
        jTextFieldPassword.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldPassword.setText("Password");

        jButtonCopy.setText("Copy");
        jButtonCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyActionPerformed(evt);
            }
        });

        jLabelPasswordCopied.setForeground(new java.awt.Color(204, 0, 0));
        jLabelPasswordCopied.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButtonCrearPass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jSliderLongitudPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxSimbolos)
                                    .addComponent(jCheckBoxNumeros))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxMinusculas)
                                    .addComponent(jCheckBoxMayusculas))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxCaracterEspecialMinusculas)
                                    .addComponent(jCheckBoxCaracterEspecialMayusculas)))
                            .addComponent(jLabelLongitudPass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNoPass, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPasswordCopied)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMinusculas)
                    .addComponent(jCheckBoxNumeros)
                    .addComponent(jCheckBoxCaracterEspecialMinusculas))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMayusculas)
                    .addComponent(jCheckBoxSimbolos)
                    .addComponent(jCheckBoxCaracterEspecialMayusculas))
                .addGap(18, 18, 18)
                .addComponent(jLabelLongitudPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderLongitudPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonCrearPass)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoPass)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelPasswordCopied)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderLongitudPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderLongitudPassStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderLongitudPassStateChanged

    private void jCheckBoxMinusculasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMinusculasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMinusculasStateChanged

    private void jCheckBoxNumerosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxNumerosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNumerosStateChanged

    private void jCheckBoxCaracterEspecialMinusculasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxCaracterEspecialMinusculasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCaracterEspecialMinusculasStateChanged

    private void jCheckBoxCaracterEspecialMayusculasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxCaracterEspecialMayusculasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCaracterEspecialMayusculasStateChanged

    private void jCheckBoxSimbolosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSimbolosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSimbolosStateChanged

    private void jCheckBoxMayusculasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMayusculasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMayusculasStateChanged

    private void jButtonCrearPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearPassActionPerformed

    private void jCheckBoxCaracterEspecialMinusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCaracterEspecialMinusculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCaracterEspecialMinusculasActionPerformed

    private void jButtonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCopyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCopy;
    public javax.swing.JButton jButtonCrearPass;
    public javax.swing.JCheckBox jCheckBoxCaracterEspecialMayusculas;
    public javax.swing.JCheckBox jCheckBoxCaracterEspecialMinusculas;
    public javax.swing.JCheckBox jCheckBoxMayusculas;
    public javax.swing.JCheckBox jCheckBoxMinusculas;
    public javax.swing.JCheckBox jCheckBoxNumeros;
    public javax.swing.JCheckBox jCheckBoxSimbolos;
    public javax.swing.JLabel jLabelLongitudPass;
    public javax.swing.JLabel jLabelNoPass;
    public javax.swing.JLabel jLabelPasswordCopied;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JSlider jSliderLongitudPass;
    public javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables
}
